alias madafaka-chuck-the-fuck-out-all-dockers=scripts/remove_all_docker_containers_and_images
alias gradlew='./gradlew'
alias gcb='./gradlew clean build'
alias gb='./gradlew build'
alias s-jenkins='ssh ci.pojo.pl'
alias s-hub='ssh hub.pojo.pl'
alias s-youtrack='ssh youtrack.pojo.pl'
alias s-teamcity='ssh teamcity.pojo.pl'
alias s-teamcity-agent='ssh agent.teamcity.pojo.pl'
