alias madafaka-chuck-the-fuck-out-all-dockers=scripts/remove_all_docker_containers_and_images
alias gradlew='./gradlew'
alias gcb='./gradlew clean build'
alias gb='./gradlew build'
alias ssh-ci='ssh ci.pojo.pl'
alias ssh-jenkins='ssh ci.pojo.pl'
alias ssh-hub='ssh hub.pojo.pl'
alias ssh-youtrack='ssh youtrack.pojo.pl'
alias ssh-teamcity='ssh teamcity.pojo.pl'
